# Generated by Django 3.2.2 on 2021-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noodles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/noodles')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/pizza')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/salad')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
